spring.datasource.url: jdbc:mysql://localhost:3306/dbgreens?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username: root
spring.datasource.password: "00400040"
spring.jpa.hibernate.ddl-auto: update